spring:
  application:
    name: blackjack

  data:
    mongodb:
      database: blackjack_games
      uri: mongodb://localhost:27017


#  r2dbc:
##    url: r2dbc:mysql://localhost:3306/blackjack_players?serverTimezone=UTC
#    url: r2dbc:mysql://localhost:3306/blackjack_players
#    username: root
#    password: 1707

  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}

server:
  port: 8080


# swagger
# http://localhost:8080/v3/api-docs
# http://localhost:8080/swagger-ui/index.html#/

# index.html
# http://localhost:8080/index.html