spring:
#  r2dbc:
#    url: r2dbc:mysql://mysql-db:3306/blackjack_players
#    username: root
#    password: 1707
#
#  data:
#    mongodb:
#      uri: mongodb://mongo-db:27017/blackjack_games
#
#server:
#  port: 8080

  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}

#server:
#  port: 8080
server:
  port: ${PORT:8080}